# Margin Base Softmax
margin_list: [1.0, 0.5, 0.0]
network: r50
resume: false
save_all_states: false
log_dir: tmp

embedding_size: 512

# Partial FC
sample_rate: 1
interclass_filtering_threshold: 0

fp16: false
batch_size: 128

# Optimizer
optimizer: sgd
lr: 0.1
momentum: 0.9
weight_decay: 5e-4

# Logging
log_output: tmp
verbose: 2000
frequent: 10

# DALI
dali: false
dali_aug: false

# Gradient accumulation
gradient_acc: 1

# Seed
seed: 2048

# DataLoader
num_workers: 2

# WandB
wandb_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
suffix_run_name: null
using_wandb: false
wandb_entity: entity
wandb_project: project
wandb_log_all: true
save_artifacts: false
wandb_resume: false
