seed_everything: 2048

trainer:
  max_epochs: 50
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  log_every_n_steps: 100
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ./logs
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: ./checkpoints/save_clip
        every_n_train_steps: 25000
        save_last: true
        save_top_k: -1
        filename: model_{step}

model:
  config:
    weight_decay: 5e-4
    init_lr_swapper: 0.01
    init_lr_dis: 0.01
    optimizer: adamw8bit
    lr_schedule_step: 5
    lr_schedule_gamma: 0.9
    adv_sess: 200000
    gradient_acc: 2
    visualize: true
    log_dir: tmp
    output: ./checkpoints
  device: auto

data:
  db_path: ./datasets/new
  batch_size: 2
  num_workers: 8

# ckpt_path: ./ckpts/experiment
